version: '2.1'
executors:
    golang:
        docker:
            - image: golang:1.13.1-alpine

jobs:
    lint:
        executor: golang
        working_directory: ~/repo
        steps:
            - run:
                name: Install requirements
                command: apk add git openssh-client
            - checkout
            - run:
                name: Lint
                command: gofmt -d -e -s .

    test:
        executor: golang
        working_directory: ~/repo
        steps:
            - run:
                name: Install requirements
                command: apk add git openssh-client
            - checkout
            - run:
                name: Download modules
                command: go mod download
            - run:
                name: Test
                environment:
                    CGO_ENABLED: 0
                command: go test ./...

workflows:
    version: '2.1'
    tests:
        jobs:
            - lint
            - test
