version: '2.1'
executors:
    golang:
        docker:
            - image: golang:1.12.9-alpine

jobs:
    lint:
        executor: golang
        working_directory: ~/repo
        steps:
            - run:
                name: Install requirements
                command: apk add git openssh-client
            - checkout
            - run:
                name: Lint
                command: gofmt -d -e -s .

workflows:
    version: '2.1'
    tests:
        jobs:
            - lint
